# codai.models - Model parsing and templates
from .manager import (
    ModelManager,
    WhisperServerManager,
    MultiModelManager,
    model_manager,
    multi_model_manager,
)
from .parser import (
    ModelParserDispatcher,
    BaseParser,
    QwenParser,
    DeepSeekParser,
    LlamaParser,
    MistralParser,
    ClaudeParser,
    CommandRParser,
    GemmaParser,
    GrokParser,
    PhiParser,
    ApexBig50Parser,
    OpenAIFormatter,
    ToolCallParser,
    ModelParserAdapter,
    filter_repetition,
    filter_malformed_content,
    cleanup_control_tokens,
    validate_json_complete,
    format_tools_for_prompt,
)

from .templates import AgenticTemplateManager

__all__ = [
    'ModelManager',
    'WhisperServerManager',
    'MultiModelManager',
    'model_manager',
    'multi_model_manager',
    'ModelParserDispatcher',
    'BaseParser',
    'QwenParser',
    'DeepSeekParser',
    'LlamaParser',
    'MistralParser',
    'ClaudeParser',
    'CommandRParser',
    'GemmaParser',
    'GrokParser',
    'PhiParser',
    'ApexBig50Parser',
    'OpenAIFormatter',
    'ToolCallParser',
    'ModelParserAdapter',
    'AgenticTemplateManager',
    'filter_repetition',
    'filter_malformed_content',
    'cleanup_control_tokens',
    'validate_json_complete',
    'format_tools_for_prompt',
]
